import 'package:flame_audio/flame_audio.dart';

/// Manages game audio (SFX + BGM).
/// Sound assets live in assets/audio/. SFX are 16-bit WAV at 22kHz,
/// generated by scripts/audio/generate_sfx.py.
class AudioSystem {
  static bool _initialized = false;
  static bool sfxEnabled = true;
  static bool bgmEnabled = true;
  static double sfxVolume = 0.7;
  static double bgmVolume = 0.45;
  static String? _currentBgm;

  static const _sfxFiles = <String>[
    'shoot.wav', 'shoot_heavy.wav', 'shoot_laser.wav',
    'hit.wav', 'crit.wav',
    'player_hurt.wav',
    'pickup_gold.wav', 'pickup_item.wav',
    'pickup_weapon.wav', 'pickup_talent.wav',
    'slime_die.wav',
    'footstep.wav',
    'level_up.wav',
    'door_open.wav',
    'explosion.wav',
  ];

  static Future<void> init() async {
    if (_initialized) return;
    _initialized = true;
    try {
      await FlameAudio.audioCache.loadAll(_sfxFiles);
    } catch (_) {
      // missing audio assets shouldn't crash the game
    }
  }

  static void _play(String name, {double? vol}) {
    if (!sfxEnabled) return;
    try {
      FlameAudio.play(name, volume: vol ?? sfxVolume);
    } catch (_) {}
  }

  // === SFX ===
  static void playShoot([String style = 'normal']) {
    switch (style) {
      case 'heavy':
        _play('shoot_heavy.wav', vol: sfxVolume * 0.85);
        break;
      case 'laser':
        _play('shoot_laser.wav', vol: sfxVolume * 0.85);
        break;
      default:
        _play('shoot.wav', vol: sfxVolume * 0.45);
    }
  }

  static void playHit() => _play('hit.wav', vol: sfxVolume * 0.6);
  static void playCrit() => _play('crit.wav', vol: sfxVolume * 0.85);
  static void playEnemyDeath() => _play('slime_die.wav', vol: sfxVolume * 0.7);
  static void playPlayerHit() => _play('player_hurt.wav', vol: sfxVolume * 0.85);
  static void playPickupGold() => _play('pickup_gold.wav', vol: sfxVolume * 0.55);
  static void playPickupItem() => _play('pickup_item.wav', vol: sfxVolume * 0.6);
  static void playPickupWeapon() => _play('pickup_weapon.wav', vol: sfxVolume * 0.7);
  static void playPickupTalent() => _play('pickup_talent.wav', vol: sfxVolume * 0.7);
  static void playLevelUp() => _play('level_up.wav', vol: sfxVolume * 0.75);
  static void playDoorOpen() => _play('door_open.wav', vol: sfxVolume * 0.6);
  static void playExplosion() => _play('explosion.wav', vol: sfxVolume * 0.85);
  static void playFootstep() => _play('footstep.wav', vol: sfxVolume * 0.3);

  // === BGM ===
  static Future<void> _bgm(String track) async {
    if (!bgmEnabled) return;
    if (_currentBgm == track) return;
    _currentBgm = track;
    try {
      await FlameAudio.bgm.stop();
      await FlameAudio.bgm.play(track, volume: bgmVolume);
    } catch (_) {}
  }

  static Future<void> playMenuBgm() => _bgm('bgm_menu.wav');
  static Future<void> playDungeonBgm() => _bgm('bgm_dungeon.wav');
  static Future<void> playCombatBgm() => _bgm('bgm_combat.wav');
  static Future<void> playBossBgm() => _bgm('bgm_combat.wav');

  static Future<void> stopBgm() async {
    _currentBgm = null;
    try { await FlameAudio.bgm.stop(); } catch (_) {}
  }

  static void pauseBgm() {
    try { FlameAudio.bgm.pause(); } catch (_) {}
  }

  static void resumeBgm() {
    try { FlameAudio.bgm.resume(); } catch (_) {}
  }

  static void toggleSfx() => sfxEnabled = !sfxEnabled;
  static void toggleBgm() {
    bgmEnabled = !bgmEnabled;
    if (!bgmEnabled) {
      stopBgm();
    }
  }
}
